### ISSUE TITLE
Asprin and Clingo 5.5.0 mismatch

### ISSUE THREAD

**Issue by Namakeya** [potassco/clingo#324]
I installed latest Asprin (3.1.1) and Clingo (5.5.0) but it didn't work.
(base) C:\Users\adamh>asprin --version
Traceback (most recent call last):
  File "C:\Users\adamh\anaconda3\Scripts\asprin-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\adamh\anaconda3\lib\site-packages\asprin\asprin.py", line 29, in main
    from .src.main import main as main_module
  File "C:\Users\adamh\anaconda3\lib\site-packages\asprin\src\main\main.py", line 36, in <module>
    from ..spec_parser    import           spec_parser
  File "C:\Users\adamh\anaconda3\lib\site-packages\asprin\src\spec_parser\spec_parser.py", line 30, in <module>
    from .spec_lexer import Lexer
  File "C:\Users\adamh\anaconda3\lib\site-packages\asprin\src\spec_parser\spec_lexer.py", line 27, in <module>
    from ..utils import utils
  File "C:\Users\adamh\anaconda3\lib\site-packages\asprin\src\utils\utils.py", line 87, in <module>
    NO_SIGN = clingo.ast.Sign.NoSign
AttributeError: module 'clingo' has no attribute 'ast'

It works with Clingo 5.4.1 now.
Using Anaconda 4.10.3 , Python 3.8.10.

**Comment by tortinator** [comment]
I'm afraid asprin hasn't been upgraded yet, and @javier-romero, who could confirm, is on vacation.
Thanks for letting us know!

**Comment by Namakeya** [comment]
I understand. Thank you for your reply.
